name: ME@c-base
favicon: null
layout_spectrum: 1
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#25231d'
    - '#4c4b45'
    - '#d9d8d6'
    - '#a8a7a1'
    - '#928d88'
  brandStrength: 0.5
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
